services:
 tutorial_app:
    image: todo_app:latest
    container_name: todo_app
    ports:
     - 8080:8080
    restart: unless-stopped

 db:
   image: mysql:latest
   container_name: mysql_db 
   ports:
     - 3306:3306
   environment:
     - MYSQL_ROOT_PASSWORD=rmGQk5CHy2R7O8
     - MYSQL_DATABASE=todo_app_db
   volumes:
     - ${HOME}/db_volume:/var/lib/mysql
   restart: unless-stopped
