services:
 tutorial_app:
    image: todo_app:latest
    container_name: todo_app
    ports:
     - 8080:8080
    restart: unless-stopped

 db:
   image: mysql:latest
   container_name: mysql_db 
   environment:
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
     - MYSQL_DATABASE=${DB_NAME}
   volumes:
     - ${HOME}/db_volume:/var/lib/mysql
   restart: unless-stopped
