services:
 tutorial_app:
    image: todo_app:latest
    container_name: todo_app
    ports:
     - 8080:8080
    restart: unless-stopped
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

 db:
   image: mysql:latest
   container_name: mysql_db 
   environment:
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
     - MYSQL_DATABASE=${DB_NAME}
   volumes:
     - ${HOME}/db_volume:/var/lib/mysql
   restart: unless-stopped
