name: Deploy AWS Infra for the todo-app

on:
  push:
    paths:
      - "terraform/**" # Trigger if any Terraform file changes
      - "!terraform/ecr-repo/**" #Exclude the ecr-repo directory
  workflow_run:
    workflows: ["Build and Push Docker Image to Private ECR"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: ./terraform
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: terraform plan -var "db_username=${DB_USERNAME}" -var "db_password=${DB_PASSWORD}" -var "db_name=${DB_NAME}"

      - name: Apply Terraform
        if: github.ref == 'refs/heads/master' # Only apply on master branch
        working-directory: ./terraform
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: terraform apply -auto-approve -var "db_username=${DB_USERNAME}" -var "db_password=${DB_PASSWORD}" -var "db_name=${DB_NAME}"
