name: Set Up ECR Repository

on:
  push:
    branches:
      - master
    paths:
      - "terraform/ecr-repo/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: ./terraform/ecr-repo
        run: terraform init

      - name: Apply Terraform
        working-directory: ./terraform/ecr-repo
        run: terraform apply -auto-approve
